export const ORGANIZATION = {
  REGISTER: 'REGISTER_ORGANIZATION',
  EDIT: 'EDIT_ORGANIZATION',
  GET_TIME: 'GET_TIME_ORGANIZATION',
};

export const ACCOUNT = {
  REGISTER: 'REGISTER_ACCOUNT',
  EDIT: 'EDIT_ACCOUNT',
  GET_TIME: 'GET_TIME_ACCOUNT',
};

export const MESSAGE = {
  REGISTER: 'REGISTER_MESSAGE',
  EDIT: 'EDIT_MESSAGE',
  GET_TIME: 'GET_TIME_MESSAGE',
};

export const SCHEDULE = {
  REGISTER: 'REGISTER_SCHEDULE',
  EDIT: 'EDIT_SCHEDULE',
  GET_TIME: 'GET_TIME_SCHEDULE',
};

